dagsterCloud:
  deployment: prod

dagsterCloudAgent:
  resources:
    limits:
      cpu: "250m"
      memory: "512Mi"
      ephemeral-storage: "10Mi"
    requests:
      cpu: "250m"
      memory: "512Mi"
      ephemeral-storage: "10Mi"

extraManifests:
  - apiVersion: v1
    kind: LimitRange
    metadata:
      name: default-container-resources
      namespace: dagster-cloud
    spec:
      limits:
        - default:
            cpu: "250m"
            memory: "512Mi"
            ephemeral-storage: "10Mi"
          defaultRequest:
            cpu: "250m"
            memory: "512Mi"
            ephemeral-storage: "10Mi"
          type: Container
