dagsterCloud:
  deployment: prod
dagsterCloudAgent:
  resources:
    limits:
      cpu: 250m
      memory: 512Mi
      ephemeral-storage: 10Mi
    requests:
      cpu: 250m
      memory: 512Mi
      ephemeral-storage: 10Mi      